# Generated by Django 3.1 on 2020-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePage', '0005_auto_20201121_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='news',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
