# Generated by Django 3.1 on 2020-11-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePage', '0006_auto_20201121_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentinnews',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
