# Generated by Django 3.1 on 2020-11-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePage', '0009_auto_20201123_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentinnews',
            options={'ordering': ['-time'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
