# Generated by Django 3.1 on 2020-12-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, verbose_name='Заголовок')),
        ),
    ]
