# Generated by Django 3.1 on 2020-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20201216_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='companie',
            options={'verbose_name': 'Компанию', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Задерживаеться', 'Задерживаеться'), ('Завершено', 'Завершено'), ('Отклонено', 'Отклонено')], default='В ожидании', max_length=60, verbose_name='Статус'),
        ),
    ]
