# Generated by Django 3.1 on 2020-12-17 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0007_auto_20201217_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Доверенная компания'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companie', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='market.product', verbose_name='Товар'),
        ),
    ]
