# Generated by Django 3.1 on 2020-12-26 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0010_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='market.promocode', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='count_using',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество использованей'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
