# Generated by Django 3.1 on 2020-12-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20201227_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='sale',
        ),
    ]
