# Generated by Django 3.1 on 2020-12-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20201227_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='code',
            field=models.SlugField(null=True),
        ),
    ]
