# Generated by Django 3.1 on 2020-12-27 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20201227_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дать создания промо акции'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='work_to',
            field=models.DateTimeField(null=True, verbose_name='Работает до'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='market.promocode', verbose_name='Скидка'),
        ),
    ]
