# Generated by Django 3.1 on 2020-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20201227_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='work_is',
            field=models.ManyToManyField(blank=True, related_name='work_is', to='market.Product', verbose_name='Работают с'),
        ),
    ]
