# Generated by Django 3.1 on 2020-12-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_logpromocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogPromoCode',
        ),
    ]
