# Generated by Django 3.1 on 2020-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_delete_logpromocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо акцию', 'verbose_name_plural': 'Промо акции'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.SlugField(default='', help_text='Оставьте пустым, чтоб код сгенерировался случайный код', null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='count_using',
            field=models.IntegerField(default=1, verbose_name='Количество использованей'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='work_to',
            field=models.DateTimeField(blank=True, help_text='Оставьте пустым, чтоб работало неограниченое кол. времяни', null=True, verbose_name='Работает до'),
        ),
    ]
