# Generated by Django 3.1 on 2020-12-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20201229_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.SlugField(default='-', help_text="Напишите '-', чтоб код сгенерировался случайный код", null=True),
        ),
    ]
