# Generated by Django 3.1 on 2020-12-24 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20201224_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата основания')),
                ('verified', models.BooleanField(default=False, verbose_name='Доверенный клан')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Работники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
