# Generated by Django 3.1 on 2020-12-26 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_guild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guild',
            options={'verbose_name': 'Клан', 'verbose_name_plural': 'Кланы'},
        ),
        migrations.AlterField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Участики'),
        ),
    ]
